/**
 * ObjectQL
 * Copyright (c) 2026-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface Attachment extends ObjectDoc {
    /**
     * File Name
     */
    name: string;
    /**
     * File URL
     */
    file_url: any;
    /**
     * File Size (bytes)
     */
    file_size?: number;
    /**
     * MIME Type
     */
    file_type?: string;
    /**
     * Related Object Name
     */
    related_to?: string;
    /**
     * Related Record ID
     */
    related_id?: string;
    /**
     * Uploaded By
     */
    uploaded_by?: string | number;
    /**
     * Description
     */
    description?: string;
    /**
     * Tags (comma-separated)
     */
    tags?: string;
}
