/**
 * ObjectQL
 * Copyright (c) 2026-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface CrmContact extends ObjectDoc {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Full Name
     */
    full_name?: any;
    /**
     * Email
     */
    email?: string;
    /**
     * Phone
     */
    phone?: string;
    /**
     * Mobile
     */
    mobile?: string;
    /**
     * Job Title
     */
    title?: string;
    /**
     * Department
     */
    department?: string;
    /**
     * Account
     */
    account: string | number;
    /**
     * Contact Owner
     */
    owner?: string | number;
    /**
     * Lead Source
     */
    lead_source?: string;
    /**
     * LinkedIn Profile
     */
    linkedin_url?: string;
    /**
     * Notes
     */
    description?: string;
    /**
     * Status
     */
    status?: string;
}
