/**
 * ObjectQL
 * Copyright (c) 2026-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface CrmLead extends ObjectDoc {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Company
     */
    company?: string;
    /**
     * Job Title
     */
    title?: string;
    /**
     * Email
     */
    email?: string;
    /**
     * Phone
     */
    phone?: string;
    /**
     * Status
     */
    status: string;
    /**
     * Lead Source
     */
    lead_source?: string;
    /**
     * Lead Rating
     */
    rating?: string;
    /**
     * Lead Owner
     */
    owner?: string | number;
    /**
     * Industry
     */
    industry?: string;
    /**
     * Annual Revenue
     */
    annual_revenue?: number;
    /**
     * Number of Employees
     */
    employees?: number;
    /**
     * Description
     */
    description?: string;
    /**
     * Conversion Date
     */
    converted_date?: Date | string;
    /**
     * Converted Account
     */
    converted_account?: string | number;
    /**
     * Converted Contact
     */
    converted_contact?: string | number;
    /**
     * Converted Opportunity
     */
    converted_opportunity?: string | number;
}
