/**
 * ObjectQL
 * Copyright (c) 2026-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface CrmOpportunity extends ObjectDoc {
    /**
     * Opportunity Name
     */
    name: string;
    /**
     * Account
     */
    account: string | number;
    /**
     * Amount
     */
    amount: number;
    /**
     * Expected Close Date
     */
    close_date: Date | string;
    /**
     * Stage
     */
    stage: string;
    /**
     * Probability (%)
     */
    probability?: number;
    /**
     * Opportunity Type
     */
    type?: string;
    /**
     * Lead Source
     */
    lead_source?: string;
    /**
     * Opportunity Owner
     */
    owner: string | number;
    /**
     * Next Step
     */
    next_step?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Known Competitors
     */
    competitors?: string;
}
