/**
 * ObjectQL
 * Copyright (c) 2026-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface FinanceExpense extends ObjectDoc {
    /**
     * Expense Number
     */
    expense_number: string;
    /**
     * Employee
     */
    employee: string | number;
    /**
     * Expense Date
     */
    expense_date: Date | string;
    /**
     * Category
     */
    category: string;
    /**
     * Amount
     */
    amount: number;
    /**
     * Currency
     */
    currency?: string;
    /**
     * Merchant/Vendor
     */
    merchant?: string;
    /**
     * Description
     */
    description: string;
    /**
     * Receipt Attachment
     */
    receipt_url?: any;
    /**
     * Status
     */
    status: string;
    /**
     * Approved By
     */
    approved_by?: string | number;
    /**
     * Approval Time
     */
    approved_at?: Date | string;
    /**
     * Reimbursement Date
     */
    reimbursed_at?: Date | string;
    /**
     * Department
     */
    department?: string | number;
    /**
     * Related Project
     */
    project?: string | number;
}
