/**
 * ObjectQL
 * Copyright (c) 2026-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface FinanceBudget extends ObjectDoc {
    /**
     * Budget Name
     */
    name: string;
    /**
     * Fiscal Year
     */
    fiscal_year: number;
    /**
     * Period
     */
    period?: string;
    /**
     * Department
     */
    department?: string | number;
    /**
     * Project
     */
    project?: string | number;
    /**
     * Category
     */
    category?: string;
    /**
     * Allocated Amount
     */
    allocated_amount: number;
    /**
     * Spent Amount
     */
    spent_amount?: number;
    /**
     * Remaining Amount
     */
    remaining_amount?: number;
    /**
     * Start Date
     */
    start_date: Date | string;
    /**
     * End Date
     */
    end_date: Date | string;
    /**
     * Status
     */
    status?: string;
    /**
     * Budget Owner
     */
    owner?: string | number;
    /**
     * Notes
     */
    notes?: string;
}
