/**
 * ObjectQL
 * Copyright (c) 2026-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface HrDepartment extends ObjectDoc {
    /**
     * Department Name
     */
    name: string;
    /**
     * Department Code
     */
    code: string;
    /**
     * Parent Department
     */
    parent_department?: string | number;
    /**
     * Department Manager
     */
    manager?: string | number;
    /**
     * Cost Center Code
     */
    cost_center?: string;
    /**
     * Primary Location
     */
    location?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Status
     */
    status?: string;
}
