/**
 * ObjectQL
 * Copyright (c) 2026-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface Organization extends ObjectDoc {
    /**
     * Organization Name
     */
    name: string;
    /**
     * Organization Code
     */
    code?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Parent Organization
     */
    parent?: string | number;
    /**
     * Manager
     */
    manager?: string | number;
    /**
     * Description
     */
    description?: string;
    /**
     * Organization Logo
     */
    logo?: any;
    /**
     * Address
     */
    address?: string;
    /**
     * Website
     */
    website?: string;
    /**
     * Phone Number
     */
    phone?: string;
    /**
     * Contact Email
     */
    email?: string;
    /**
     * Status
     */
    status?: string;
}
