/**
 * ObjectQL
 * Copyright (c) 2026-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface ProjectMilestone extends ObjectDoc {
    /**
     * Milestone Name
     */
    name: string;
    /**
     * Project
     */
    project: string | number;
    /**
     * Description
     */
    description?: string;
    /**
     * Target Date
     */
    due_date: Date | string;
    /**
     * Completion Date
     */
    completed_date?: Date | string;
    /**
     * Status
     */
    status: string;
    /**
     * Milestone Owner
     */
    owner?: string | number;
    /**
     * Deliverables
     */
    deliverables?: string;
    /**
     * Success Criteria
     */
    success_criteria?: string;
}
