packages:
  - packages/foundation/*
  - packages/drivers/*
  - packages/runtime/*
  - packages/tools/*
  - packages/starters/*
  - examples/scenarios/*
  - examples/plugins/*
  - examples/tutorials/*

onlyBuiltDependencies:
  - esbuild
  - sqlite3
  - unrs-resolver
