packages:
  - packages/foundation/*
  - packages/drivers/*
  - packages/runtime/*
  - packages/tools/*
  - examples/quickstart/*
  - examples/integrations/*
  - examples/showcase/*

onlyBuiltDependencies:
  - esbuild
  - sqlite3
  - unrs-resolver
