packages:
  - packages/foundation/*
  - packages/drivers/*
  - packages/runtime/*
  - packages/tools/*
  - packages/objectstack/*
  - packages/protocols/*
  - ../spec/packages/*
  - examples/quickstart/*
  - examples/integrations/*
  - examples/showcase/*
  - examples/drivers/*
  - apps/*

onlyBuiltDependencies:
  - esbuild
  - sqlite3
  - unrs-resolver
