// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface User extends ObjectDoc {
    /**
     * Full Name
     */
    name: string;
    /**
     * Email Address
     */
    email: string;
    /**
     * Username
     */
    username?: string;
    /**
     * Mobile Phone
     */
    mobile?: string;
    /**
     * Profile Picture
     */
    avatar?: any;
    status?: string;
    role?: string;
    /**
     * Last Login Time
     */
    last_login_at?: Date | string;
    /**
     * Preferred Language
     */
    locale?: string;
    /**
     * Timezone
     */
    timezone?: string;
}
