/**
 * Swagger UI Plugin for ObjectStack
 * Copyright (c) 2026-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import type { RuntimePlugin, RuntimeContext } from '@objectql/types';
import { readFileSync } from 'fs';
import { join } from 'path';

/**
 * Configuration for the Swagger UI Plugin
 */
export interface SwaggerUIPluginConfig {
    /**
     * Base path where Swagger UI will be served
     * @default "/api-docs"
     */
    basePath?: string;
    
    /**
     * Path to the OpenAPI specification endpoint
     * If not provided, will try to use REST protocol's OpenAPI endpoint
     * @default "/api/openapi.json"
     */
    specUrl?: string;
    
    /**
     * Port to listen on (if running standalone server)
     * If not provided, will attach to existing HTTP server
     */
    port?: number;
    
    /**
     * Custom Swagger UI configuration
     */
    swaggerOptions?: Record<string, any>;
    
    /**
     * Custom page title
     * @default "ObjectQL API Documentation"
     */
    title?: string;
}

/**
 * Swagger UI Protocol Plugin
 * 
 * Provides an interactive API documentation and debugging interface using Swagger UI.
 * This plugin serves the Swagger UI interface and connects it to the OpenAPI
 * specification generated by the REST protocol plugin.
 * 
 * Key Features:
 * - Interactive API documentation
 * - Try-it-out functionality for testing API endpoints
 * - Request/response visualization
 * - Schema exploration
 * - Authentication support
 * - Automatic integration with REST protocol
 * 
 * @example
 * ```typescript
 * import { ObjectStackKernel } from '@objectstack/runtime';
 * import { RestPlugin } from '@objectql/protocol-rest';
 * import { SwaggerUIPlugin } from '@objectql/protocol-swagger-ui';
 * 
 * const kernel = new ObjectStackKernel([
 *   new RestPlugin({ basePath: '/api' }),
 *   new SwaggerUIPlugin({ 
 *     basePath: '/api-docs',
 *     title: 'My API Documentation'
 *   })
 * ]);
 * await kernel.start();
 * 
 * // Access Swagger UI at: http://localhost:PORT/api-docs
 * ```
 */
export class SwaggerUIPlugin implements RuntimePlugin {
    name = '@objectql/protocol-swagger-ui';
    version = '4.0.0';
    
    private config: Required<SwaggerUIPluginConfig>;
    private engine?: any;
    private ctx?: RuntimeContext;

    constructor(config: SwaggerUIPluginConfig = {}) {
        this.config = {
            basePath: config.basePath || '/api-docs',
            specUrl: config.specUrl || '/api/openapi.json',
            port: config.port,
            swaggerOptions: config.swaggerOptions || {},
            title: config.title || 'ObjectQL API Documentation'
        } as any;
    }

    /**
     * Install hook - called during kernel initialization
     */
    async install(ctx: RuntimeContext): Promise<void> {
        console.log(`[${this.name}] Installing Swagger UI plugin...`);
        this.ctx = ctx;
        this.engine = ctx.engine || (ctx as any).getKernel?.();
    }

    /**
     * Start hook - called when kernel starts
     */
    async onStart(ctx: RuntimeContext): Promise<void> {
        if (!this.engine) {
            throw new Error('Swagger UI plugin not initialized. Install hook must be called first.');
        }

        // Check for shared HTTP server (Hono)
        const httpServer = (this.ctx as any)?.getService?.('http-server');
        if (httpServer && httpServer.app) {
            console.log(`[${this.name}] 🔗 Attaching to shared HTTP server...`);
            this.attachToHono(httpServer.app);
            return;
        }

        console.log(`[${this.name}] ⚠️  No shared HTTP server found. Swagger UI requires an HTTP server to function.`);
        console.log(`[${this.name}] Please ensure a protocol plugin with HTTP server is loaded (e.g., REST, GraphQL, OData).`);
    }

    /**
     * Stop hook - called when kernel stops
     */
    async onStop(ctx: RuntimeContext): Promise<void> {
        console.log(`[${this.name}] Stopping Swagger UI...`);
    }

    /**
     * Attach Swagger UI to a Hono application
     */
    private attachToHono(app: any): void {
        const { basePath, specUrl, title, swaggerOptions } = this.config;
        
        console.log(`[${this.name}] Mounting Swagger UI at ${basePath}`);

        // Serve Swagger UI HTML page
        app.get(basePath, (c: any) => {
            const html = this.generateSwaggerUIHTML(specUrl, title, swaggerOptions);
            return c.html(html);
        });

        // Serve Swagger UI static assets
        try {
            const swaggerUiPath = require.resolve('swagger-ui-dist');
            const swaggerUiAssetPath = swaggerUiPath.replace(/index\.js$/, '');
            
            // Serve swagger-ui.css
            app.get(`${basePath}/swagger-ui.css`, (c: any) => {
                try {
                    const css = readFileSync(join(swaggerUiAssetPath, 'swagger-ui.css'), 'utf8');
                    c.header('Content-Type', 'text/css');
                    return c.body(css);
                } catch (error) {
                    console.error(`[${this.name}] Error serving CSS:`, error);
                    return c.text('CSS not found', 404);
                }
            });

            // Serve swagger-ui-bundle.js
            app.get(`${basePath}/swagger-ui-bundle.js`, (c: any) => {
                try {
                    const js = readFileSync(join(swaggerUiAssetPath, 'swagger-ui-bundle.js'), 'utf8');
                    c.header('Content-Type', 'application/javascript');
                    return c.body(js);
                } catch (error) {
                    console.error(`[${this.name}] Error serving JS bundle:`, error);
                    return c.text('JS bundle not found', 404);
                }
            });

            // Serve swagger-ui-standalone-preset.js
            app.get(`${basePath}/swagger-ui-standalone-preset.js`, (c: any) => {
                try {
                    const js = readFileSync(join(swaggerUiAssetPath, 'swagger-ui-standalone-preset.js'), 'utf8');
                    c.header('Content-Type', 'application/javascript');
                    return c.body(js);
                } catch (error) {
                    console.error(`[${this.name}] Error serving standalone preset:`, error);
                    return c.text('Standalone preset not found', 404);
                }
            });

            console.log(`[${this.name}] 📚 Swagger UI available at ${basePath}`);
            console.log(`[${this.name}] 📄 OpenAPI spec will be loaded from ${specUrl}`);
            
        } catch (error) {
            console.error(`[${this.name}] Error setting up Swagger UI assets:`, error);
        }
    }

    /**
     * Generate the Swagger UI HTML page
     */
    private generateSwaggerUIHTML(specUrl: string, title: string, swaggerOptions: Record<string, any>): string {
        const options = {
            url: specUrl,
            dom_id: '#swagger-ui',
            deepLinking: true,
            presets: [
                'SwaggerUIBundle.presets.apis',
                'SwaggerUIStandalonePreset'
            ],
            plugins: [
                'SwaggerUIBundle.plugins.DownloadUrl'
            ],
            layout: 'StandaloneLayout',
            ...swaggerOptions
        };

        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <link rel="stylesheet" type="text/css" href="${this.config.basePath}/swagger-ui.css" />
    <style>
        html {
            box-sizing: border-box;
            overflow: -moz-scrollbars-vertical;
            overflow-y: scroll;
        }
        
        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }
        
        body {
            margin: 0;
            padding: 0;
        }
        
        .swagger-ui .topbar {
            background-color: #1a1a2e;
        }
        
        .swagger-ui .topbar .download-url-wrapper {
            display: none;
        }
        
        .topbar-wrapper {
            display: flex;
            align-items: center;
            padding: 10px 0;
        }
        
        .topbar-wrapper .link {
            font-size: 1.5em;
            font-weight: bold;
            text-decoration: none;
            color: #fff;
            font-family: sans-serif;
        }
        
        .topbar-wrapper .link::before {
            content: "⚡ ";
        }
    </style>
</head>

<body>
    <div id="swagger-ui"></div>

    <script src="${this.config.basePath}/swagger-ui-bundle.js" charset="UTF-8"></script>
    <script src="${this.config.basePath}/swagger-ui-standalone-preset.js" charset="UTF-8"></script>
    <script>
        window.onload = function() {
            window.ui = SwaggerUIBundle(${JSON.stringify(options, null, 2)});
        };
    </script>
</body>
</html>`;
    }
}
