// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface Projects extends ObjectDoc {
    /**
     * Name
     */
    name: string;
    status?: string;
    priority?: string;
    description?: string;
    /**
     * Project Owner
     */
    owner?: string;
    /**
     * Total Budget
     */
    budget?: number;
    /**
     * Start Date
     */
    start_date?: Date | string;
    /**
     * End Date
     */
    end_date?: Date | string;
}
