// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface FinanceInvoice extends ObjectDoc {
    /**
     * Invoice Number
     */
    invoice_number: string;
    /**
     * Customer Account
     */
    account: string | number;
    /**
     * Invoice Date
     */
    invoice_date: Date | string;
    /**
     * Due Date
     */
    due_date: Date | string;
    /**
     * Subtotal
     */
    subtotal: number;
    /**
     * Tax Amount
     */
    tax_amount?: number;
    /**
     * Discount Amount
     */
    discount_amount?: number;
    /**
     * Total Amount
     */
    total_amount: number;
    /**
     * Paid Amount
     */
    paid_amount?: number;
    /**
     * Balance Due
     */
    balance?: number;
    /**
     * Status
     */
    status: string;
    /**
     * Payment Terms
     */
    payment_terms?: string;
    /**
     * Currency
     */
    currency?: string;
    /**
     * Billing Address
     */
    billing_address?: string;
    /**
     * Notes
     */
    notes?: string;
    /**
     * Internal Notes
     */
    internal_notes?: string;
}
