// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface FinancePayment extends ObjectDoc {
    /**
     * Payment Number
     */
    payment_number: string;
    /**
     * Related Invoice
     */
    invoice?: string | number;
    /**
     * Customer Account
     */
    account: string | number;
    /**
     * Payment Date
     */
    payment_date: Date | string;
    /**
     * Payment Amount
     */
    amount: number;
    /**
     * Payment Method
     */
    payment_method: string;
    /**
     * Currency
     */
    currency?: string;
    /**
     * Reference/Transaction Number
     */
    reference_number?: string;
    /**
     * Status
     */
    status: string;
    /**
     * Processed By
     */
    processed_by?: string | number;
    /**
     * Notes
     */
    notes?: string;
}
