// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface HrEmployee extends ObjectDoc {
    /**
     * Employee Number
     */
    employee_number: string;
    /**
     * System User Account
     */
    user?: string | number;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Full Name
     */
    full_name?: any;
    /**
     * Work Email
     */
    email: string;
    /**
     * Work Phone
     */
    phone?: string;
    /**
     * Mobile Phone
     */
    mobile?: string;
    /**
     * Department
     */
    department: string | number;
    /**
     * Position
     */
    position: string | number;
    /**
     * Direct Manager
     */
    manager?: string | number;
    /**
     * Hire Date
     */
    hire_date: Date | string;
    /**
     * Termination Date
     */
    termination_date?: Date | string;
    /**
     * Employment Type
     */
    employment_type?: string;
    /**
     * Status
     */
    status: string;
    /**
     * Base Salary
     */
    salary?: number;
    /**
     * Office Location
     */
    location?: string;
    /**
     * Emergency Contact Name
     */
    emergency_contact_name?: string;
    /**
     * Emergency Contact Phone
     */
    emergency_contact_phone?: string;
    /**
     * Notes
     */
    notes?: string;
}
