// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface HrTimesheet extends ObjectDoc {
    /**
     * Employee
     */
    employee: string | number;
    /**
     * Work Date
     */
    work_date: Date | string;
    /**
     * Clock In Time
     */
    clock_in?: Date | string;
    /**
     * Clock Out Time
     */
    clock_out?: Date | string;
    /**
     * Total Hours
     */
    total_hours?: number;
    /**
     * Regular Hours
     */
    regular_hours?: number;
    /**
     * Overtime Hours
     */
    overtime_hours?: number;
    /**
     * Break Hours
     */
    break_hours?: number;
    /**
     * Work Type
     */
    work_type?: string;
    /**
     * Status
     */
    status: string;
    /**
     * Approved By
     */
    approved_by?: string | number;
    /**
     * Approval Time
     */
    approved_at?: Date | string;
    /**
     * Notes
     */
    notes?: string;
}
