// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface ProjectProject extends ObjectDoc {
    /**
     * Project Name
     */
    name: string;
    /**
     * Project Code
     */
    code: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Status
     */
    status: string;
    /**
     * Priority
     */
    priority?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Customer Account
     */
    account?: string | number;
    /**
     * Project Manager
     */
    owner: string | number;
    /**
     * Department
     */
    department?: string | number;
    /**
     * Start Date
     */
    start_date: Date | string;
    /**
     * Target End Date
     */
    end_date?: Date | string;
    /**
     * Actual End Date
     */
    actual_end_date?: Date | string;
    /**
     * Project Budget
     */
    budget?: number;
    /**
     * Estimated Hours
     */
    estimated_hours?: number;
    /**
     * Actual Hours
     */
    actual_hours?: number;
    /**
     * Completion %
     */
    completion_percentage?: number;
}
