// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface ProjectTask extends ObjectDoc {
    /**
     * Task Name
     */
    name: string;
    /**
     * Project
     */
    project: string | number;
    /**
     * Parent Task
     */
    parent_task?: string | number;
    /**
     * Description
     */
    description?: string;
    /**
     * Status
     */
    status: string;
    /**
     * Priority
     */
    priority?: string;
    /**
     * Assigned To
     */
    assigned_to?: string | number;
    /**
     * Due Date
     */
    due_date?: Date | string;
    /**
     * Completion Date
     */
    completed_date?: Date | string;
    /**
     * Estimated Hours
     */
    estimated_hours?: number;
    /**
     * Actual Hours
     */
    actual_hours?: number;
    /**
     * Milestone
     */
    milestone?: string | number;
    /**
     * Tags
     */
    tags?: string;
}
