name: product
label: Product
fields:
  name: 
    type: text
    required: true
    searchable: true
  sku:
    type: text
    required: true
    unique: true
  stock_quantity:
    type: number
    defaultValue: 0
  price:
    type: currency
