// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface FinanceExpense extends ObjectDoc {
    /**
     * Expense Number
     */
    expense_number: string;
    /**
     * Employee
     */
    employee: string | number;
    /**
     * Expense Date
     */
    expense_date: Date | string;
    category: string;
    /**
     * Amount
     */
    amount: number;
    currency?: string;
    /**
     * Merchant/Vendor
     */
    merchant?: string;
    /**
     * Description
     */
    description: string;
    /**
     * Receipt Attachment
     */
    receipt_url?: any;
    status: string;
    /**
     * Approved By
     */
    approved_by?: string | number;
    /**
     * Approval Time
     */
    approved_at?: Date | string;
    /**
     * Reimbursement Date
     */
    reimbursed_at?: Date | string;
    /**
     * Department
     */
    department?: string | number;
    /**
     * Related Project
     */
    project?: string | number;
}
