// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface FinanceBudget extends ObjectDoc {
    /**
     * Budget Name
     */
    name: string;
    /**
     * Fiscal Year
     */
    fiscal_year: number;
    period?: string;
    /**
     * Department
     */
    department?: string | number;
    /**
     * Project
     */
    project?: string | number;
    category?: string;
    /**
     * Allocated Amount
     */
    allocated_amount: number;
    /**
     * Spent Amount
     */
    spent_amount?: number;
    /**
     * Remaining Amount
     */
    remaining_amount?: number;
    /**
     * Start Date
     */
    start_date: Date | string;
    /**
     * End Date
     */
    end_date: Date | string;
    status?: string;
    /**
     * Budget Owner
     */
    owner?: string | number;
    /**
     * Notes
     */
    notes?: string;
}
