// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface KitchenSink extends ObjectDoc {
    /**
     * Simple Text
     */
    simple_text: string;
    /**
     * Multi-line Text
     */
    long_text?: string;
    /**
     * Markdown Content
     */
    rich_content?: string;
    /**
     * HTML Content
     */
    raw_html?: string;
    /**
     * Integer Count
     */
    count?: number;
    /**
     * Price
     */
    price?: number;
    /**
     * Progress
     */
    progress?: number;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Due Date
     */
    due_date?: Date | string;
    /**
     * Meeting (Date & Time)
     */
    meeting_time?: Date | string;
    /**
     * Alarm Time
     */
    alarm?: Date | string;
    /**
     * Status
     */
    status?: string;
    /**
     * Tags
     */
    tags?: string;
    /**
     * Email
     */
    email_address?: string;
    /**
     * Phone
     */
    phone_number?: string;
    /**
     * Website URL
     */
    website?: string;
    /**
     * Avatar
     */
    profile_pic?: any;
    /**
     * Attachment document
     */
    attachment?: any;
    /**
     * Image Gallery
     */
    gallery?: any[];
    /**
     * Secret Code
     */
    secret_code?: string;
    /**
     * GPS Coordinates
     */
    coords?: any;
    /**
     * JSON Metadata
     */
    metadata?: any;
    /**
     * Vector Embedding
     */
    embedding?: number[];
    /**
     * Related Project
     */
    related_project?: string | number;
}
