// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface User extends ObjectDoc {
    /**
     * Employee Record
     */
    employee?: string | number;
    email: any;
    /**
     * Employee ID
     */
    employee_id?: string;
    /**
     * Department
     */
    department?: string | number;
    /**
     * Office Location
     */
    office_location?: string;
    /**
     * Two-Factor Auth Enabled
     */
    two_factor_enabled?: boolean;
}
