/**
 * ObjectQL
 * Copyright (c) 2026-present ObjectStack Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface User extends ObjectDoc {
    /**
     * Employee Record
     */
    employee?: string | number;
    email: any;
    /**
     * Employee ID
     */
    employee_id?: string;
    /**
     * Department
     */
    department?: string | number;
    /**
     * Office Location
     */
    office_location?: string;
    /**
     * Two-Factor Auth Enabled
     */
    two_factor_enabled?: boolean;
}
