// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface CrmAccount extends ObjectDoc {
    /**
     * Account Name
     */
    name: string;
    /**
     * Account Number
     */
    account_number?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Industry
     */
    industry?: string;
    /**
     * Annual Revenue
     */
    annual_revenue?: number;
    /**
     * Number of Employees
     */
    employees?: number;
    /**
     * Website
     */
    website?: string;
    /**
     * Phone
     */
    phone?: string;
    /**
     * Billing Address
     */
    billing_address?: string;
    /**
     * Shipping Address
     */
    shipping_address?: string;
    /**
     * Account Owner
     */
    owner?: string | number;
    /**
     * Parent Account
     */
    parent_account?: string | number;
    /**
     * Description
     */
    description?: string;
    /**
     * Status
     */
    status?: string;
}
