// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface HrDepartment extends ObjectDoc {
    /**
     * Department Name
     */
    name: string;
    /**
     * Department Code
     */
    code: string;
    /**
     * Parent Department
     */
    parent_department?: string | number;
    /**
     * Department Manager
     */
    manager?: string | number;
    /**
     * Cost Center Code
     */
    cost_center?: string;
    /**
     * Primary Location
     */
    location?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Status
     */
    status?: string;
}
