// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface HrPosition extends ObjectDoc {
    /**
     * Position Title
     */
    title: string;
    /**
     * Position Code
     */
    code: string;
    /**
     * Position Level
     */
    level?: string;
    /**
     * Department
     */
    department?: string | number;
    /**
     * Reports To Position
     */
    reports_to?: string | number;
    /**
     * Minimum Salary
     */
    min_salary?: number;
    /**
     * Maximum Salary
     */
    max_salary?: number;
    /**
     * Job Description
     */
    description?: string;
    /**
     * Requirements & Qualifications
     */
    requirements?: string;
    /**
     * Key Responsibilities
     */
    responsibilities?: string;
    /**
     * Status
     */
    status?: string;
}
