// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface Organization extends ObjectDoc {
    /**
     * Organization Name
     */
    name: string;
    /**
     * Organization Code
     */
    code?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Parent Organization
     */
    parent?: string | number;
    /**
     * Manager
     */
    manager?: string | number;
    /**
     * Description
     */
    description?: string;
    /**
     * Organization Logo
     */
    logo?: any;
    /**
     * Address
     */
    address?: string;
    /**
     * Website
     */
    website?: string;
    /**
     * Phone Number
     */
    phone?: string;
    /**
     * Contact Email
     */
    email?: string;
    /**
     * Status
     */
    status?: string;
}
