// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface ProjectTimesheetEntry extends ObjectDoc {
    /**
     * Employee
     */
    employee: string | number;
    /**
     * Project
     */
    project: string | number;
    /**
     * Task
     */
    task?: string | number;
    /**
     * Work Date
     */
    work_date: Date | string;
    /**
     * Hours Worked
     */
    hours: number;
    /**
     * Work Description
     */
    description?: string;
    /**
     * Billable
     */
    billable?: boolean;
    /**
     * Status
     */
    status?: string;
    /**
     * Approved By
     */
    approved_by?: string | number;
    /**
     * Approval Time
     */
    approved_at?: Date | string;
}
