// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface User extends ObjectDoc {
    /**
     * Employee Record
     */
    employee?: string | number;
    /**
     * Email Address
     */
    email: string;
    /**
     * Employee ID
     */
    employee_id?: string;
    /**
     * Department
     */
    department?: string | number;
    /**
     * Office Location
     */
    office_location?: string;
    /**
     * Two-Factor Auth Enabled
     */
    two_factor_enabled?: boolean;
    /**
     * Full Name
     */
    name: string;
    /**
     * Username
     */
    username?: string;
    /**
     * Mobile Phone
     */
    mobile?: string;
    /**
     * Profile Picture
     */
    avatar?: any;
    status?: string;
    role?: string;
    /**
     * Last Login Time
     */
    last_login_at?: Date | string;
    /**
     * Preferred Language
     */
    locale?: string;
    /**
     * Timezone
     */
    timezone?: string;
}
