// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface Projects extends ObjectDoc {
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Priority
     */
    priority?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Owner
     */
    owner?: string;
    /**
     * Budget
     */
    budget?: number;
    /**
     * Start Date
     */
    start_date?: Date | string;
    /**
     * End Date
     */
    end_date?: Date | string;
    /**
     * Approved By
     */
    approved_by?: string;
    /**
     * Approved At
     */
    approved_at?: Date | string;
    /**
     * Approval Comment
     */
    approval_comment?: string;
}
