// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface Tasks extends ObjectDoc {
    /**
     * Name
     */
    name: string;
    /**
     * Project
     */
    project?: string | number;
    /**
     * Due Date
     */
    due_date?: Date | string;
    /**
     * Completed
     */
    completed?: boolean;
    /**
     * Priority
     */
    priority?: string;
    /**
     * Assignee
     */
    assigned_to?: string;
    /**
     * Estimated Hours
     */
    estimated_hours?: number;
}
