// Auto-generated by ObjectQL. DO NOT EDIT.
import { ObjectDoc } from '@objectql/types';

export interface Tasks extends ObjectDoc {
    name: string;
    project?: string | number;
    due_date?: Date | string;
    completed?: boolean;
    priority?: string;
    /**
     * Assignee
     */
    assigned_to?: string;
    /**
     * Estimated Hours
     */
    estimated_hours?: number;
}
