// Auto-generated by ObjectQL. DO NOT EDIT.
// (Simulated for this example)

export interface Project {
    _id: string;
    name: string;
    status: 'planned' | 'in_progress' | 'completed';
    priority: 'low' | 'normal' | 'high';
    description?: string;
    owner?: string;
    budget?: number;
    start_date?: Date | string;
    end_date?: Date | string;
}

export interface Task {
    _id: string;
    name: string;
    project: string; // ID
    due_date?: Date | string;
    completed: boolean;
    priority: 'low' | 'medium' | 'high';
    assigned_to?: string;
    estimated_hours?: number;
}
